version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:ec589ea6cf22b380bf85be70aad4cda36cb5cf0d174816b2eb5e771c8f94182d
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Pruning Dependencies
          command: npm prune
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Compiling Code
          command: npm run build
      - run:
          name: Testing Code
          command: npm run cover
      - run:
          name: Linting Code
          command: npm run lint
      - run:
          name: Checking Code Duplication
          command: npm run duplication -- --limit 10
      - deploy:
          name: Semantic Release
          command: npm run semantic-release
